/*
 * =====================================================================================
 *
 *       Filename:  ProductType.H
 *
 *    Description:  
 *
 *        Created:  09/22/2016 12:55:41 PM
 *       Compiler:  g++
 *
 *         Author:  Soumya Prasad Ukil
 *        Company:  AlgoEngine
 *
 * =====================================================================================
 */

namespace Algo
{
  enum ProductType
  {
    CURRENCY
  };
}
