/*
 * =====================================================================================
 *
 *       Filename:  AlgoOrderType.H
 *
 *    Description:  Order type enum
 *
 *        Created:  05/01/2017 06:40:00 AM
 *       Compiler:  g++
 *
 *         Author:  Soumya Prasad Ukil
 *        Company:  AlgoEngine
 *
 * =====================================================================================
 */

#ifndef AlgoOrderType_H
#define AlgoOrderType_H

namespace Algo
{
  enum AlgoOrderType
  {
    Primary=1,
    SecondaryLimit,
    SecondaryStop
  };
}

#endif
