/*
 * =====================================================================================
 *
 *       Filename:  DBOperation.H
 *
 *    Description:  Database operation if it is update/insert/delete
 *
 *        Created:  05/01/2017 06:40:00 AM
 *       Compiler:  g++
 *
 *         Author:  Soumya Prasad Ukil
 *        Company:  AlgoEngine
 *
 * =====================================================================================
 */

#ifndef DBOperation_H
#define DBOperation_H

namespace Algo
{
  enum DBOperation
  {
    Insert,
    Update,
    Delete
  };
}

#endif
