/*
 * =====================================================================================
 *
 *       Filename:  Side.H
 *
 *    Description:
 *
 *        Created:  09/21/2016 12:05:17 PM
 *       Compiler:  g++
 *
 *         Author:  Soumya Prasad Ukil
 *        Company:  AlgoEngine
 *
 * =====================================================================================
 */

#ifndef Side_H
#define Side_H

namespace Algo
{
  enum Side
  {
    Side_BUY = 0,
    Side_SELL = 1,
    Side_BID = 0,
    Side_ASK = 1
  };
}

#endif // Side_H
