#! /bin/bash

filename=$1
symbol=$2".csv"
grep -iREn "Ticker $2 (BID|ASK)" $1 > $symbol
sed -i 's/\[Nanex MD\]//g' $symbol
sed -i 's/price://g' $symbol
sed -i "s/  Ticker $2 \(.*\) / \1/g" $symbol
sed -i 's/,/./' $symbol
sed -Ei 's/[0-9]+:2017/2017/' $symbol
sed -i 's/ BID[ ]\+\([0-9.]\+\)/,\1,/g' $symbol
sed -i 's/ ASK[ ]\+\([0-9.]\+\)/\1/g' $symbol
sed -i 's/:/./g' $symbol
sed -i '1iTimestamp,Bid,Ask' $symbol
